name: Build Docker image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
#        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "scripts/build.sh"
        target: "/root/"
    - name: build docker
      uses: appleboy/ssh-action@master
#      env:
#        DOCKER_USERNAME: ${{ secret.DOCKER_USERNAME }}
#        DOCKER_PASSWORD: ${{ secret.DOCKER_PASSWORD }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
#        port: ${{ secrets.PORT }}
#        envs: DOCKER_USERNAME,DOCKER_PASSWORD
        script: /root/scripts/build.sh "${{ secret.DOCKER_USERNAME }}" "${{ secret.DOCKER_PASSWORD }}" 
#    - name: Executing remote  command
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.HOST }}
#        USERNAME: ${{ secrets.USERNAME }}
##        PORT: ${{ secrets.PORT }}
#        KEY: ${{ secrets.SSHKEY }}
#        script: ls -la
